version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=1000d"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    ports:
      - "9090:9090"
    user: root

  node-exporter:
    image: quay.io/prometheus/node-exporter:v0.18.1
    command: --path.rootfs /host
    volumes:
      - /:/host:ro,rslave
    ports:
      - "9100"
    pid: "host"

  grafana:
    image: grafana/grafana:6.7.1
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    user: root

